{
    "score": "84",
    "comments": "====================\nTests for Part 1:\ntest_case09 (workspace.testing_suite_full.PartATestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 670, in test_case09\n    self.run_with_params(9, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\nSuccesses: 9\nFailures: 1\n\n====================\nTests for Part 2:\ntest_case01 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 699, in test_case01\n    self.run_with_params(1, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case02 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 702, in test_case02\n    self.run_with_params(2, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case04 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 708, in test_case04\n    self.run_with_params(4, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case05 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 711, in test_case05\n    self.run_with_params(5, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case07 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 717, in test_case07\n    self.run_with_params(7, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case09 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 723, in test_case09\n    self.run_with_params(9, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case10 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 726, in test_case10\n    self.run_with_params(10, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\nSuccesses: 3\nFailures: 7\n\n====================\nOverall Score: 84\n"
}