{
    "score": "101",
    "comments": "====================\nTests for Part 1:\ntest_case09 (workspace.testing_suite_full.PartATestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 670, in test_case09\n    self.run_with_params(9, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\nSuccesses: 9\nFailures: 1\n\n====================\nTests for Part 2:\ntest_case04 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 708, in test_case04\n    self.run_with_params(4, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case07 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 717, in test_case07\n    self.run_with_params(7, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case09 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 723, in test_case09\n    self.run_with_params(9, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\nSuccesses: 7\nFailures: 3\n\nScore above 100: 112 capped to 101!====================\nOverall Score: 101\n"
}